import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="flex flex-col md:flex-row min-h-screen md:p-6 2xl:px-28 gap-2">
          <Sidebar />
          <div className="border-2 p-2 w-full rounded-xl flex-row">
            <Navbar />
            <div className="flex-1 justify-center items-center p-4">
              <div className='flex justify-between'>
                {children}
              </div>
            </div>
          </div>
        </div>
      </ThemeProvider>
      </body>
    </html>
  );
}
